### ISSUE TITLE
Implement support for background image of BackgroundChanger extension

### ISSUE THREAD

**Issue by rocket1138** [darklinkpower/Nova-X#8] opened 2024-06-02 06:33 UTC
### Bug Description

When trying to use the BackgroundChanger Plugin with Nova-X, Background game image stays the same and doesn't change like its supposed to.

Tried with some other of your themes more specifically [Helium](https://github.com/darklinkpower/Helium) and [Mythic](https://github.com/darklinkpower/Mythic) and the issue seems limited to Nova-X

### Screenshots

Video Test with Nova-X

https://github.com/darklinkpower/Nova-X/assets/47755554/fd6ecab1-13b0-4adb-81ac-4aa974f26b09

Video Test with Helium

https://github.com/darklinkpower/Nova-X/assets/47755554/27cdd361-21bc-4dc1-8340-2034ed2f8e28

**Comment by darklinkpower** [comment] 2024-06-02 09:33
The reason is that I've implemented support for the plugin in those themes but not yet in this one.

**Comment by ciaron88** [comment] 2024-09-21 09:50
any update on a fix for this? BackgroundChanger works fine for the Poster/Cover just not the the background image?

**Comment by darklinkpower** [comment] 2024-09-21 18:59
Only update is that I've not worked on it yet.

**Comment by darklinkpower** [comment] 2024-09-26 15:11
Support added in new update.

**Closed by darklinkpower** 2024-09-26 15:11 UTC
Labels: bug

**Comment by ElTioRata** [comment] 2025-01-08 02:44
Doesn't work :(

**Comment by ElTioRata** [comment] 2025-01-11 20:29
Okay, now it does work. The problem is not related to the theme itself, it's [an issue with the plugin itself](https://github.com/Lacro59/playnite-backgroundchanger-plugin/issues/48).
